### ISSUE TITLE
EXTMEM peripheral is missing

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp32c3#1]
Perhaps its merged into another peripheral? I couldn't find it though.

**Comment by jessebraham** [comment]
It seems this peripheral missing from the source files entirely. I've opened an issue internally for this.

**Comment by jessebraham** [comment]
Managed to get this one fixed pretty quick! The `EXTMEM` peripheral is now present (see 7087c23) and I have published `0.3.0` of this crate which includes it.
