### ISSUE TITLE
0.3.0 fails to build on Docs.rs

### ISSUE THREAD

**Issue by D1plo1d** [esp-rs/esp32c3#2]
The docs for version 0.3.0 fail to build on docs.rs: https://docs.rs/esp32c3/0.3.0/esp32c3/

In the meantime the 0.2.0 docs are still viewable here: https://docs.rs/esp32c3/0.2.0/esp32c3/

**Comment by MabezDev** [comment]
I think we're hitting a docs.rs build time limit here, usually if the build fails on docs.rs it will give you a link to the error log. I know stm32-rs folks ran into the same issue, I'm not sure how they solved this - possibly an exception from the docs.rs folks?

**Comment by TheButlah** [comment]
This seems especially problematic since right now it says that the page doesn't exist.

I believe you can reach out to the docs.rs team on the official rust discord - someone can probably say what to do there.

**Comment by TheButlah** [comment]
From the docs.rs team on discord:
> Hi,yes, there is a  build time limit, seehttps://docs.rs/about/builds#hitting-resource-limits Did you see any errors in the build logs for this version?Any resource limitation would be visible in there

> we do have huge crates with millions of documentation files on docs.rs, so it's totally possible. stm32ral is one of the examples.The docs.rs team can increase some limits on a case-by-case base, which is probably what the stm-rs people did.

Do reach out to them - they are very responsive and easy to talk to

**Comment by jessebraham** [comment]
According to the answers received in Discord, this may actually be an issue with [docs.rs](https://docs.rs). Apparently the build succeeded (which I would expect it to, as this crate is smaller than `esp32` which builds; see the [build log](https://docs.rs/crate/esp32c3/latest/builds)) but for whatever reason the docs were not uploaded. I will try to keep this issue updated as new information comes in.

**Comment by jessebraham** [comment]
The docs are now available at [https://docs.rs/esp32c3/latest/esp32c3/](https://docs.rs/esp32c3/latest/esp32c3/).
